version: '3.7'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: ./
    command: /app/start.sh
    depends_on:
        - "mail"
  mail:
    image: bytemark/smtp
    restart: always

networks:
  default:
    external:
      name: healthcheck-network

